version: '3.8'

services:
  node-todo-app:
    image: /${DOCKER_IMAGE}:v37
    ports:
      - "8080:8000"
    networks:
      - my-custom-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
        reservations:
          cpus: "0.25"
          memory: "128M"

networks:
  my-custom-network:
    external: true
